project:
  type: book
  output-dir: docs

book:
  title: "Analyzing Canadian Demographic and Housing Data"
  publisher: "MountainMath Software and Analytics"
  author: 
    - name: "Jens von Bergmann"
      email: "jens@mountainmath.ca"
      corresponding: true
      affiliations:
        - name: "MountainMath Software and Analytics"
          city: "Vancouver"
          state: "British Columbia"
  date: "2022-04-01"
  subtitle: "Building skills and community to analyze Canadian demographic and housing data"
  search: true
  twitter-card:
    description: "Building skills and community to analyze Canadian demographic and housing data"
    card-style: summary_large_image
    image: cover.png
  open-graph:
    description: "Building skills and community to analyze Canadian demographic and housing data"
    image: cover.png
  site-url: "https://mountainmath.github.io/canadian_data/"
  downloads: [pdf, epub]
  citations-hover: true
  citeproc: true
  fig-responsive: true
  # fig-dpi: 150
  # fig-width: 8
  # fig-height: 6
  # fig-format: png
  sidebar:
    style: docked
    #background: light
    logo: cover.png
  top-level-division: part
  page-footer: 
    left: "Copyright 2022, Jens von Bergmann" 
    right: 
      - icon: github
        href: https://github.com/mountainmath
      - icon: twitter 
        href: https://twitter.com/vb_jens
      - icon: linkedin 
        href: https://www.linkedin.com/in/vb-jens/
  chapters:
    - index.qmd
    - intro.qmd
    - part: intro/getting_started.qmd
      chapters:
      - intro/intro_to_r.qmd
      - intro/intro_cansim.qmd
      - intro/intro_cancensus.qmd
      - intro/intro_cmhc.qmd
      - intro/tongfen.qmd
    - part: basic_descriptive/basic_descriptive.qmd
      chapters:
      #- basic_descriptive/high_income_new_housing.qmd
      - basic_descriptive/cerb.qmd
      - basic_descriptive/cars_vs_suvs.qmd
      - basic_descriptive/under_construction.qmd
      - basic_descriptive/geography_of_income_change.qmd
      - basic_descriptive/toronto_children.qmd
      - basic_descriptive/number_of_household_maintainers.qmd
    - part: advanced_descriptive/advanced_descriptive.qmd
      chapters:
      - advanced_descriptive/advanced_descriptive_bc_migration.qmd
    - references.qmd

bibliography: references.bib
# csl: citestyle.csl

execute:
  message: false
  warning: false
  cache: true

format:
  html:
    fig-dpi: 150
    fig-width: 8
    fig-height: 6
    fig-format: png
    fig-responsive: true
    code-fold: show
    code-tools: true
    code-summary: "Code"
    code-link: true
    #theme: cosmo
    theme:
      dark: darkly
      light: flatly
    code-copy: true
  titlepage-pdf:
    fig-format: png
    titlepage: classic-lined
    documentclass: scrbook
    titlepage-logo: cover.png
    classoption: ["oneside", "open=any"]
    number-sections: true
    titlepage-theme:
      page-align: "center"
      elements:
        - "\\titleblock"
        - "\\authorblock"
        - "\\vfill"
        - "\\logoblock"
        - "\\footerblock"
  # pdf:
  #   documentclass: scrreprt
  #   fig-format: png
  epub:
    cover-image: cover.png
    fig-format: png
    
editor: visual

