project:
  type: book
  output-dir: docs

book:
  title: "Analyzing Canadian Demographic and Housing Data"
  author: "Jens von Bergmann"
  date: "2022-04-01"
  description: "Building skills and community to analyze Canadian demographic and housing data."
  search: true
  twitter-card: true
  image: cover.png
  card-style: summary_large_image
  site-url: "https://mountainmath.github.io/canadian_data/"
  downloads: [pdf, epub]
  citations-hover: true
  citeproc: true
  fig-responsive: true
  # fig-dpi: 150
  # fig-width: 8
  # fig-height: 6
  # fig-format: png
  sidebar:
    style: docked
    background: light
    logo: cover.png
  top-level-division: part
  code-fold: show
  page-footer: 
    left: "Copyright 2022, Jens von Bergmann" 
    right: 
      - icon: github
        href: https://github.com/mountainmath
      - icon: twitter 
        href: https://twitter.com/vb_jens
      - icon: linkedin 
        href: https://www.linkedin.com/in/vb-jens/
  chapters:
    - index.qmd
    - intro.qmd
    - part: intro/intro_to_r.qmd
      chapters:
      - intro/intro_cansim.qmd
      - intro/intro_cancensus.qmd
      - intro/intro_cmhc.qmd
      - intro/tongfen.qmd
    - part: basic_descriptive/basic_descriptive.qmd
      chapters:
      #- basic_descriptive/high_income_new_housing.qmd
      - basic_descriptive/cerb.qmd
      - basic_descriptive/cars_vs_suvs.qmd
      - basic_descriptive/geography_of_income_change.qmd
    - part: advanced_descriptive/advanced_descriptive.qmd
      chapters:
      - advanced_descriptive/advanced_descriptive_bc_migration.qmd
    - references.qmd

bibliography: references.bib
# csl: citestyle.csl

execute:
  message: false
  warning: false
  cache: true

format:
  html:
    fig-dpi: 150
    fig-width: 8
    fig-height: 6
    fig-format: png
    fig-responsive: true
    #theme: cosmo
    theme:
      light: flatly
      dark: darkly
    code-copy: true
  pdf:
    documentclass: scrreprt
    fig-format: png
  epub:
    cover-image: cover.png
    fig-format: png
    
editor: visual

