project:
  type: book
  output-dir: docs

book:
  title: "Analyzing Candian Demographic and Housing Data"
  author: "Jens von Bergmann"
  date: "2022-04-01"
  description: "Building skills and community to analyse Canadian demographic and housing data."
  search: true
  page-footer: 
    left: "Copyright 2022, Jens von Bergmann" 
    right: 
      - icon: github
        href: https://github.com/mountainmath
      - icon: twitter 
        href: https://twitter.com/vb_jens
      - icon: linkedin 
        href: https://www.linkedin.com/in/vb-jens/
  chapters:
    - index.qmd
    - intro.qmd
    - part: intro/intro_to_r.qmd
      chapters:
      - intro/intro_cansim.qmd
      - intro/intro_cancensus.qmd
      - intro/intro_cmhc.qmd
    - part: basic_descriptive/basic_descriptive.qmd
      chapters:
      #- basic_descriptive/high_income_new_housing.qmd
      - basic_descriptive/cars_vs_suvs.qmd
    - part: advanced_descriptive/advanced_descriptive.qmd
      chapters:
      - advanced_descriptive/advanced_descriptive_bc_migration.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

