# Getting started with R and RStudio

Statistics Canada produces a lot of high quality demographic and economic data for Canada. CMHC complements this with housing data, and municipalities across Canada often provide relevant data through their Open Data portals.

## R and RStudio

We will be working in R and the [RStudio IDE](https://www.rstudio.com/products/rstudio/download/ "Download RStudio"), although using a different editor like [Visual Studio Code](https://visualstudio.microsoft.com) works just as well, especially if you are already familiar with it. Within R we will be operating within the [tidyverse framework](https://www.tidyverse.org), a group of R packages that work well together and allow for intuitive operations on data via pipes.

While an introduction to R is part of the goal of this book, an we will slowly build up skills as we go, we not give a systematic introduction but rather build up skills slowly as we work on concrete examples. It may be beneficial to supplement this with a [more principled introduction to **R** and the **tidyverse**](https://r4ds.had.co.nz/index.html)**.**

During the course of this book we will make heavy use of several R packages to facilitate data access, we will introduce them in this chapter.
